Final_Project/Controllers/CategoryController.cs
using Final_Project.Models;
using Final_Project.Reposatiory;
using Final_Project.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Final_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private CategoryRepository caterepo;
        public CategoryController(CategoryRepository _caterepo)
        {
            caterepo = _caterepo;
        }
        public IActionResult Index()
        {
            List<Categorie> cat = caterepo.GetCategories();
            return View(cat);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Categorie cat)
        {
            if (cat != null)
            {
                caterepo.Insert(cat);
                caterepo.Save();
                return RedirectToAction("Index");
            }

            return View("Create", cat);
        }

        public IActionResult Details(string id)
        {
            Categorie catbyid = caterepo.GetById(id);
            return View(catbyid);
        }
        [HttpGet]
        public IActionResult Edit(string id)
        {
            Categorie catbyid = caterepo.GetById(id);
            return View(catbyid);
        }
        [HttpPost]
        public IActionResult Edit(Categorie cat, string id)
        {
            if (cat != null)
            {
                caterepo.Update(id, cat);
                caterepo.Save();
                return RedirectToAction("Index");
            }
            return View(cat);
        }

        public IActionResult Delete(string id)
        {

            caterepo.Delete(id);
            caterepo.Save();
            return RedirectToAction("Index");
        }
        public IActionResult Search(string searchValue)
        {
            var filteredUsers = caterepo.SearchCategories(searchValue);

            
            return PartialView("_CatogriesTablePartial", filteredUsers); // Assuming you have a partial view for the table body
        }

        // GET: /User/ResetSearch
        public IActionResult ResetSearch()
        {
            var allUsers = caterepo.GetCategories();

            
            return PartialView("_CatogriesTablePartial", allUsers); // Assuming you have a partial view for the table body
        }





    }
}

Final_Project/Controllers/RoleController.cs
using Final_Project.Models;
using Final_Project.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Final_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {


        private readonly RoleManager<IdentityRole> roleManager;

        public RoleController(RoleManager<IdentityRole> _RoleManager)
        {
            roleManager = _RoleManager;
        }

        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }

        public IActionResult New()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> New(RoleViewModel roleVM)
        {
            if (ModelState.IsValid)
            {
                IdentityRole roleModel = new IdentityRole();
                roleModel.Name = roleVM.RoleName;
                IdentityResult result = await roleManager.CreateAsync(roleModel);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }
            return View(roleVM);
        }

        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            RoleViewModel roleVM = new RoleViewModel
            {
                RoleId = role.Id,
                RoleName = role.Name
            };

            return View(roleVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleViewModel roleVM)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = await roleManager.FindByIdAsync(roleVM.RoleId);
                if (role == null)
                {
                    return NotFound();
                }

                role.Name = roleVM.RoleName;
                IdentityResult result = await roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }
            return View(roleVM);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            IdentityResult result = await roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                // Handle the delete failure
                return RedirectToAction("Index");
            }
        }
    }
}

Final_Project/Controllers/UserController.cs
using Final_Project.Models;
using Final_Project.Reposatiory;
using Final_Project.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Plugins;
using System.Data;

namespace Final_Project.Controllers
{
    [Authorize(Roles = "Admin")]

    public class UserController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;
        RoleManager<IdentityRole> _roleManager;
        AuthorRepository _authorRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public UserController(UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
             AuthorRepository authorRepository,
             IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _authorRepository = authorRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult GetAllUsers()
        {
            var users = _userManager.Users.ToList();
            var model = users.Select(u => new UsersDetailsViewModel()
            {
                id = u.Id,
                Email = u.Email,
                Addrss = u.Address,
                Phone = u.PhoneNumber,
                Name = u.UserName,
                Role = _userManager.GetRolesAsync(u).Result.FirstOrDefault(),
                Photo = u.Photo,
                
            }).ToList();

            return View(model);
        }
        public IActionResult AddUser()
        {
            var viewmodel = new RegisterViewModel()
            {
                RoleOptions = _roleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList()
            };
            return View(viewmodel);
        }
        [HttpPost]
        public async Task< IActionResult> AddUser(RegisterViewModel model, IFormFile imageFile)
        {
            if (imageFile != null && imageFile.Length > 0)
            {
                string fileName = Path.GetFileName(imageFile.FileName);

                // Specify the path where the image will be saved
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", fileName);

                // Save the image file to the specified path
                using (var stream = new FileStream(imagePath, FileMode.Create))
                {
                    imageFile.CopyTo(stream);
                }

                // Set the Image property of the Instructor object
                model.Photo = fileName;

                if (ModelState.IsValid)
                {
                    ApplicationUser user = new ApplicationUser()
                    {
                        Email = model.Email,
                        Address = model.Addrss,
                        PhoneNumber = model.Phone,
                        UserName = model.Name,
                        Photo = model.Photo
                    };
                    var result = await _userManager.CreateAsync(user, model.Password);
                    if (result.Succeeded)
                    {

                        var selectedRole = await _roleManager.FindByNameAsync(model.Role);
                        if (selectedRole != null)
                        {
                            await _userManager.AddToRoleAsync(user, selectedRole.Name);
                            if (model.Role == "Author")
                            {
                                var author = new Author()
                                {
                                    Id = user.Id,
                                    Name = model.Name,
                                    Email = model.Email,
                                    Password = model.Password,
                                    Photo = model.Photo
                                };
                                _authorRepository.Insert(author);


                            }
                            return RedirectToAction(nameof(GetAllUsers));
                        }
                    }
                    else
                    {

                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }

                }
            }
            model.RoleOptions = _roleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            return View(model);
        }
        public async Task<IActionResult> UpdateUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var roles = await _userManager.GetRolesAsync(user);
            var model = new UsersDetailsViewModel()
            {
                id = user.Id,
                Email = user.Email,
                Addrss = user.Address,
                Phone = user.PhoneNumber,
                Name = user.UserName,
                Role = roles.FirstOrDefault(),
                Photo = user.Photo
            };
            model.RoleOptions = _roleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUser(UsersDetailsViewModel model, IFormFile? imageFile)
        {
            if(imageFile == null)
            {
                var user = await _userManager.FindByIdAsync(model.id);
                if (user != null)
                {
                    model.Photo = user.Photo;
                }

            }
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.id);
                if (user == null)
                {
                    return NotFound();
                }

                user.Email = model.Email;
                user.Address = model.Addrss;
                user.PhoneNumber = model.Phone;
                user.UserName = model.Name;

                if (imageFile != null && imageFile.Length > 0)
                {
                    string fileName = Path.GetFileName(imageFile.FileName);

                    // Specify the path where the image will be saved
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", fileName);

                    // Save the image file to the specified path
                    using (var stream = new FileStream(imagePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(stream);
                    }

                    // Set the Image property of the Instructor object
                    user.Photo = fileName;
                }


                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    var roles = await _userManager.GetRolesAsync(user);
                    await _userManager.RemoveFromRolesAsync(user, roles);
                    await _userManager.AddToRoleAsync(user, model.Role);
                    if (model.Role == "Author")
                    {
                        var author = new Author()
                        {
                            Id = user.Id,
                            Name = model.Name,
                            Email = model.Email,
                            Photo = model.Photo
                        };
                        _authorRepository.Update(author.Id,author);


                    }
                    return RedirectToAction("GetAllUsers");
                }
            }

            model.RoleOptions = _roleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            return View(model);
        }
        public async Task< IActionResult> Delete(string id)
        {
            var res=await _userManager.FindByIdAsync(id);
            var authorSearch = _authorRepository.GetAuthor(id);
            if (authorSearch != null)
            {
                _authorRepository.Delete(id);
            }
            if (res != null)
            {
                var del = await _userManager.DeleteAsync(res);
            }

            return RedirectToAction("GetAllUsers");
        }

        public async Task<IActionResult> Search(string searchValue)
        {
            var filteredUsers = await _userManager.Users
                .Where(u => u.UserName.Contains(searchValue) || u.Email.Contains(searchValue))
                .ToListAsync();

            var viewModel = MapToViewModel(filteredUsers);
            return PartialView("_UserTablePartial", viewModel); // Assuming you have a partial view for the table body
        }

        // GET: /User/ResetSearch
        public async Task<IActionResult> ResetSearch()
        {
            var allUsers = await _userManager.Users.ToListAsync();

            var viewModel = MapToViewModel(allUsers);
            return PartialView("_UserTablePartial", viewModel); // Assuming you have a partial view for the table body
        }

        private IEnumerable<UsersDetailsViewModel> MapToViewModel(IEnumerable<ApplicationUser> users)
        {
            var viewModel = users.Select(u => new UsersDetailsViewModel
            {
                id = u.Id,
                Email = u.Email,
                Addrss = u.Address,
                Phone = u.PhoneNumber,
                Name = u.UserName,
                Role = _userManager.GetRolesAsync(u).Result.FirstOrDefault(),
                Photo = u.Photo,
            });

            return viewModel;
        }
    }
}

Final_Project/Views/Shared/_CatogriesTablePartial.cshtml
@model IEnumerable<Final_Project.Models.Categorie>
<table class="table table-striped">
    <thead>
        <tr>
            <th class="table-active">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="table-active">
                @Html.DisplayNameFor(model => model.Description)
            </th>

            <th class="table-active">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-warning">Edit</a> 
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>
                </td>

            </tr>
        }
    </tbody>
</table>

Final_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Final_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Final_Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Final_Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Final_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Final_Project/Views/Shared/_Layout_Admin.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.title</title>


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/owl/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/webfont/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/css/he-fo.css">
    <link rel="stylesheet" href="~/css/style1.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
</head>

<body>
    <!-- =============== Navigation ================ -->
    <div class="containers">
        <div class="navigations">
            <ul>
                <li>
                    <a href="/Admin/Home_Admin">

                        <h2 class="title">Admin Page</h2>
                    </a>
                </li>
                <li>
                    <a href=@Url.Action("Home_Admin","Admin")>
                        <span class="icon">

                            <i class="fas fa-user-graduate cc"></i>
                        </span>
                        <span class="title">Home </span>
                    </a>
                </li>
                <li>
                    <a asp-action="GetAllUsers" asp-controller="User">
                        <span class="icon">

                            <i class="fas fa-user-graduate cc"></i>
                        </span>
                        <span class="title">Users</span>
                    </a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Category">
                        <span class="icon">

                            <i class="fas fa-chalkboard-teacher cc"></i>
                        </span>
                        <span class="title">Categories</span>
                    </a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Role">
                        <span class="icon">

                            <i class="fas fa-building cc"></i>
                        </span>
                        <span class="title">Roles</span>
                    </a>
                </li>
                <li>
                    <a asp-action="logout" asp-controller="Home">
                        <span class="icon">

                            <i class="fas fa-building cc"></i>
                        </span>
                        <span class="title">Log out</span>
                    </a>
                </li>







            </ul>
        </div>

        <!-- ========================= Main ==================== -->
        <div class="main">

            @RenderSection("HomeData", false)
            <!-- ======================= Cards ================== -->
            

            <!-- ================ Order Details List ================= -->
            <div class="details" id="details">



                        @RenderBody()




                <!-- ================= New Customers ================ -->
                <!-- ================= New Customers ================ -->

            </div>
        </div>
    </div>
    @*this form showed when you want to go to add data*@

    @RenderSection("adding_item", false)

    @*this form get it when you want to update  data *@

    @RenderSection("update_item", false)



    <!-- =========== Scripts =========  -->
    <script src="~/js/jQuery3.js"></script>
 <script src="~/js/main.js"></script>
    <script src="~/js/owl/owl.carousel.min.js"></script>
    <script src="~/css/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/webfont/fontawesome/js/all.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.0.4/popper.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <!-- ====== ionicons ======= -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>

Final_Project/Views/Shared/_UserTablePartial.cshtml
@model IEnumerable<Final_Project.ViewModels.UsersDetailsViewModel>

<table class="table table-striped">
    <thead>
        <tr>
            <th class="table-active">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="table-active">
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th class="table-active">
                @Html.DisplayNameFor(model => model.Photo)
            </th>
            <th class="table-active">
                @Html.DisplayNameFor(model => model.Addrss)
            </th>
            <th class="table-active">
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th class="table-active">
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th class="table-active">
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <img src="/images/@item.Photo" width="50px">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Addrss)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Role)
                </td>
                <td>
                    <a asp-action="UpdateUser" asp-controller="User" asp-route-id="@item.id" class="btn btn-outline-warning">Edit</a>
                    |
                    <a asp-action="Delete" asp-controller="User" asp-route-id="@item.id" class="btn btn-outline-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>